### ISSUE TITLE
AttributeError: module 'recbole.data.dataset' has no attribute 'GCSANDataset'

### ISSUE THREAD

**Issue by johnny12150** [RUCAIBox/RecBole#595] opened 2020-12-20 11:42 UTC
I am currently trying the `GCSAN`  model.
It works fine when I use the default `ml-100k` dataset.
However, when I load the preprocessed datasets such as `digientica` from Google Drive, it just won't work.
The file structure is listed as follows:
![image](https://user-images.githubusercontent.com/22369387/102712317-2cc0f600-42fb-11eb-9999-7f115b1b6d73.png)
Code in `run_recbole.py`
```python
import argparse

from recbole.quick_start import run_recbole


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--model', '-m', type=str, default='GCSAN', help='name of models')
    parser.add_argument('--dataset', '-d', type=str, default='diginetica', help='name of datasets')
    parser.add_argument('--config_files', type=str, default=None, help='config files')

    args, _ = parser.parse_known_args()

    config_file_list = args.config_files.strip().split(' ') if args.config_files else None
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
```
Full error code:
```bash
Traceback (most recent call last):
  File "C:\Users\Wade\Anaconda3\envs\rosetta_GNN\lib\site-packages\recbole\data\utils.py", line 35, in create_dataset
    return getattr(importlib.import_module('recbole.data.dataset'), config['model'] + 'Dataset')(config)
AttributeError: module 'recbole.data.dataset' has no attribute 'GCSANDataset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wade\Anaconda3\envs\rosetta_GNN\lib\site-packages\pandas\core\indexes\base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'user_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/volume/SR baseline/run_recbole.py", line 16, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "C:\Users\Wade\Anaconda3\envs\rosetta_GNN\lib\site-packages\recbole\quick_start\quick_start.py", line 38, in run_recbole
    dataset = create_dataset(config)
  File "C:\Users\Wade\Anaconda3\envs\rosetta_GNN\lib\site-packages\recbole\data\utils.py", line 40, in create_dataset
    return SequentialDataset(config)
  File "C:\Users\Wade\Anaconda3\envs\rosetta_GNN\lib\site-packages\recbole\data\dataset\sequential_dataset.py", line 38, in __init__
    super().__init__(config, saved_dataset=saved_dataset)
  File "C:\Users\Wade\Anaconda3\envs\rosetta_GNN\lib\site-packages\recbole\data\dataset\dataset.py", line 100, in __init__
    self._from_scratch()
  File "C:\Users\Wade\Anaconda3\envs\rosetta_GNN\lib\site-packages\recbole\data\dataset\dataset.py", line 113, in _from_scratch
    self._data_processing()
  File "C:\Users\Wade\Anaconda3\envs\rosetta_GNN\lib\site-packages\recbole\data\dataset\dataset.py", line 152, in _data_processing
    self._data_filtering()
  File "C:\Users\Wade\Anaconda3\envs\rosetta_GNN\lib\site-packages\recbole\data\dataset\dataset.py", line 172, in _data_filtering
    self._filter_nan_user_or_item()
  File "C:\Users\Wade\Anaconda3\envs\rosetta_GNN\lib\site-packages\recbole\data\dataset\dataset.py", line 607, in _filter_nan_user_or_item
    dropped_inter = self.inter_feat.index[self.inter_feat[field].isnull()]
  File "C:\Users\Wade\Anaconda3\envs\rosetta_GNN\lib\site-packages\pandas\core\frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Wade\Anaconda3\envs\rosetta_GNN\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'user_id'

Process finished with exit code 1

```

**Comment by linzihan-backforward** [comment] 2020-12-20 12:05
From the error code you presented, i think you used the default config_file to run the digientica dataset. In digientica, there is no _user_id_ column, which is replaced by _session_id_. You can define a new dataset config_file and set the parameter USER_ID_FIELD as session_id.  Or you can change the column name in the first line of digientica.inter. I suggest a new config_file would be better.

**Comment by johnny12150** [comment] 2020-12-20 12:19
I have tried to map the user_id into session id with a config YAML file as below:
```yaml
USER_ID_FIELD: session_id
```
However, I am still facing the same error `KeyError: 'session_id'`

**Comment by linzihan-backforward** [comment] 2020-12-20 12:38
There is another default parameter:
`load_col:
    inter: [user_id, item_id, rating, timestamp]`
You can rewrite this parameter to the column you want to load in your config YAML file.

**Comment by johnny12150** [comment] 2020-12-22 06:13
On both GCSAN and even SRGNN, the MRR@10 and MRR@20 seem odd to me, they are way too low.

> recall@20 : 0.1727    mrr@20 : 0.0439    ndcg@20 : 0.0717    hit@20 : 0.1727    precision@20 : 0.0086

**Comment by ShanleiMu** [comment] 2020-12-22 07:25
> On both GCSAN and even SRGNN, the MRR@10 and MRR@20 seem odd to me, they are way too low.
> 
> **Edit**
> SRGNN:
> 
> > recall@20 : 0.1727    mrr@20 : 0.0439    ndcg@20 : 0.0717    hit@20 : 0.1727    precision@20 : 0.0086
> 
> GCSAN:
> 
> > 'recall@20': 0.3695, 'mrr@20': 0.0843, 'ndcg@20': 0.1461, 'hit@20': 0.3695, 'precision@20': 0.0185

Could you provide more details about dataset and config settings?

**Comment by johnny12150** [comment] 2020-12-22 08:24
It's more natural now when I change the dataset to the `not_mereged` version.

> recall@20 : 0.4730    mrr@20 : 0.1648    ndcg@20 : 0.2331    hit@20 : 0.4730    precision@20 : 0.0237

Config is listed below:
```YAML
USER_ID_FIELD: session_id
load_col:
  inter: [session_id, item_id, number of times, timestamp]
epochs: 10
topk: [20]
valid_metric: MRR@20
```

**Comment by lyj1998** [comment] 2020-12-23 05:39
> It's more natural now when I change the dataset to the `not_mereged` version.
> 
> SRGNN:
> 
> > recall@20 : 0.4730    mrr@20 : 0.1648    ndcg@20 : 0.2331    hit@20 : 0.4730    precision@20 : 0.0237
> 
> Config is listed below:
> 
> ```yaml
> USER_ID_FIELD: session_id
> load_col:
>   inter: [session_id, item_id, number of times, timestamp]
> epochs: 10
> topk: [20]
> valid_metric: MRR@20
> ```
> 
> **Edit**
> So the bad performance is coming from `number of times`?
I’m not sure what the parameter `number of times` means, but it seems unnecessary for SRGNN
Perhaps you can set up your config YAML file like this to check whether the model results are normal
 ```yaml
# dataset config
USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [session_id, item_id, timestamp]

# training and evaluation
epochs: 10
topk: [20]
valid_metric: MRR@20
 ```

**Comment by johnny12150** [comment] 2020-12-24 12:08
I tried removing `number of times` from the config and yet the performance remained the same on `diginetica merged`.
Is there a way to run models such as SR-GNN, GCSAN with `merged` datasets?

**Comment by lyj1998** [comment] 2020-12-26 15:13
> I tried removing `number of times` from the config and yet the performance remained the same on `diginetica merged`.
> Is there a way to run models such as SR-GNN, GCSAN with `merged` datasets?
I selected a few sequential models to test on `diginetica merged`, and the results are shown below:

1. SRGNN:
>result: {'recall@10': 0.2037, 'mrr@10': 0.0758, 'ndcg@10': 0.1054, 'hit@10': 0.2037, 'precision@10': 0.0204}

2. GRU4Rec:
>result: {'recall@10': 0.1885, 'mrr@10': 0.0629, 'ndcg@10': 0.0919, 'hit@10': 0.1885, 'precision@10': 0.0189}

3. SASRec:
>result: {'recall@10': 0.2324, 'mrr@10': 0.0753, 'ndcg@10': 0.1115, 'hit@10': 0.2324, 'precision@10': 0.0232}

4. NARM:
>result: {'recall@10': 0.1972, 'mrr@10': 0.0704, 'ndcg@10': 0.0997, 'hit@10': 0.1972, 'precision@10': 0.0197}

Then, I use `dgl.nn.gategraphconv` to implement SRGNN, and the results of the model are similar.
Perhaps the results of the model have a lot to do with the datasets, not just the problems caused by SRGNN and GCSAN.

**Comment by johnny12150** [comment] 2020-12-26 16:04
I have run the source code of SR-GNN and self-implemented GC-SAN.
The result is quite similar to the SR-GNN paper results.
![image](https://user-images.githubusercontent.com/22369387/103155039-09a0b580-47d7-11eb-9119-56d1f2b50651.png)

**Closed** 2020-12-29 03:24 UTC
