### ISSUE TITLE
steam datasets

### ISSUE THREAD

**Issue by 1xiaohui** [RUCAIBox/RecBole#990] opened 2021-10-09 02:50 UTC
I tried to use the steam data set to get the result. I changed the item_id to product_id, and then I ran it. There was no result. Both best valid and test result were None. What should I do to change this result? I am very grateful.

**Comment by chenyuwuxin** [comment] 2021-10-09 03:26
@1xiaohui  Hello, thanks for your attention to RecBole! Could you please provide your configuration file and dataset formate? It may be due to the item_id of the configuration file is inconsistent with the field of the dataset.In addition, you can refer to [Data Settings](https://recbole.io/docs/user_guide/config/data_settings.html) to configure the dataset fields.I hope my answer can help you.

**Comment by 1xiaohui** [comment] 2021-10-09 05:36
> @1xiaohui Hello, thanks for your attention to RecBole! Could you please provide your configuration file and dataset formate? It may be due to the item_id of the configuration file is inconsistent with the item field of the dataset.In addition, you can refer to [Data Settings](https://recbole.io/docs/user_guide/config/data_settings.html) to configure the dataset fields.I hope my answer can help you.

Thank you very much for your timely answer. I think it may be the problem that there are too few datasets, because the whole datasets was not used before, but only a small part. When the whole datasets was tested, the result improved. Thank you for your attention!

**Comment by 1xiaohui** [comment] 2021-10-21 02:30
@chenyuwuxin
I encountered the following  2 problems when running steam data set with DeepFM model. How can I solve them? 

1. 

     WARNING  No columns has been loaded from [FeatureSource.ITEM]

2.
       raise AttributeError(f"'Interaction' object has no attribute '{item}'")
       AttributeError: 'Interaction' object has no attribute 'size' 


This is my config

`##model config
embedding_size: 64
mlp_hidden_size: [128, 128, 128]
dropout_prob: 0.2
##dataset config
field_separator: "\t" #指定数据集field的分隔符
seq_separator: " " #指定数据集中token_seq或者float_seq域里的分隔符
USER_ID_FIELD: user_id #指定用户id域
ITEM_ID_FIELD: product_id #指定物品id域
RATING_FIELD: ~ #rating #指定打分rating域
TIME_FIELD: timestamp #指定时间域
NEG_PREFIX: neg_ #指定负采样前缀
LABEL_FIELD: ~ #label #指定标签域
#因为数据集没有标签，所以设置一个阈值，认为rating高于该值的是正例，反之是负例
threshold: ~
#指定从什么文件里读什么列，这里就是从ml-1m.inter里面读取user_id, item_id, rating, timestamp这四列,剩下的以此类推
load_col:
    inter: [user_id, product_id]
    item: [product_id]
## training settings
epochs: 50 #训练的最大轮数
train_batch_size: 4096 #训练的batch_size
learner: adam #使用的pytorch内置优化器
learning_rate: 0.001 #学习率
training_neg_sample_num: 0 #负采样数目
eval_step: 1 #每次训练后做evalaution的次数
stopping_step: 10 #控制训练收敛的步骤数，在该步骤数内若选取的评测标准没有什么变化，就可以提前停止了
## evalution settings
eval_setting: RO_RS #对数据随机重排，设置按比例划分数据集
group_by_user: False #是否将一个user的记录划到一个组里
split_ratio: [0.8,0.1,0.1] #切分比例
metrics: ['AUC', 'LogLoss'] #评测标准
valid_metric: AUC #选取哪个评测标准作为作为提前停止训练的标准
eval_batch_size: 4096 #评测的batch_size`

**Comment by 1xiaohui** [comment] 2021-11-19 10:02
> @1xiaohui We provide a way to view specific recommendation results called **case study**.Case study is an in-depth study of the performance of a specific recommendation algorithm, which will analysis the recommendation result of some users. You can refer to [Case Study](https://recbole.io/docs/user_guide/usage/case_study.html?highlight=case) for specific details.

Hello, when I was testing case_study, the following errors occurred. The data set used is steam.

`ValueError: Neither [dataset/steam] exists in the devicenor [steam] a known dataset name.`

**Comment by chenyuwuxin** [comment] 2021-11-19 14:45
@1xiaohui In RecBole, we divide steam dataset into two types: merge type - remove duplicate interactions, and not merged - retain all interaction information.So you need to change `steam` to `steam-merged` or `steam-not-merged`.In addition,you can also manually download the steam dataset and put it under `dataset/steam`.

**Comment by 1xiaohui** [comment] 2021-11-22 06:34
Yes, I downloaded the whole steam dataset, and I only want to use the merged steam datset, so I put it under dataset/steam, but it still doesn't work.

![image](https://user-images.githubusercontent.com/88365677/142813098-fbef0265-f4fa-4b3e-abad-35ce00564b68.png)

**Comment by 1xiaohui** [comment] 2021-11-22 06:56
@chenyuwuxin At present, I only use merged data, so I put the dataset under data, but case_study reported an error. Where do I need to modify it?
![1](https://user-images.githubusercontent.com/88365677/142817279-a03d5436-b102-42d6-add7-717c55302c1b.png)

**Comment by chenyuwuxin** [comment] 2021-11-22 07:47
@1xiaohui Hello,on Linux computers,file names are case sensitive.So you need to change the name of the folder from `Steam` to `steam`.

**Comment by 1xiaohui** [comment] 2021-11-22 08:24
@chenyuwuxin I don't know why it still doesn't work properly. The system is windows. If I use other data sets such as ml-100k to get the results with BPR, I can get the results with case_study.
![2](https://user-images.githubusercontent.com/88365677/142827429-fb6b89c0-84c0-479b-a554-6d73798c28e9.png)

**Comment by chenyuwuxin** [comment] 2021-11-22 09:21
@1xiaohui There is a problem with the file path.You can try to put the `dataset` folder into `run_example` folder.
Like:
![image](https://user-images.githubusercontent.com/69251138/142835176-d25acff1-e0b2-4858-9c9d-c8a9b81231ac.png)

**Comment by 1xiaohui** [comment] 2021-11-22 10:12
@chenyuwuxin  I'm very sorry to bother you many times. What you said is quite right, but there are new problems. I hope you can help me solve them. I have too many strange points in case_study.
![4](https://user-images.githubusercontent.com/88365677/142842561-e44704c9-61f2-4f13-8215-5d17f422c3f3.png)

**Comment by chenyuwuxin** [comment] 2021-11-22 10:37
@1xiaohui What evaluation strategy did you use during the training phase?If it is not 'full', you can modify the code by referring to the following methods.
Change
https://github.com/RUCAIBox/RecBole/blob/7bd3df81edf5554ef65172601f37ef629291d7d5/recbole/quick_start/quick_start.py#L134-L135
to
```
config = checkpoint['config']
config['eval_neg_sample_args']['strategy'] = 'full'
init_logger(config)
```

**Comment by 1xiaohui** [comment] 2021-11-22 10:59
@chenyuwuxin 
This is my .yaml profile.
`#model config
embedding_size: 10
##dataset config
field_separator: "\t" #指定数据集field的分隔符
seq_separator: " " #指定数据集中token_seq或者float_seq域里的分隔符
USER_ID_FIELD: user_id #指定用户id域
ITEM_ID_FIELD: product_id #指定物品id域
RATING_FIELD: play_hours #指定打分rating域
TIME_FIELD: timestamp #指定时间域
NEG_PREFIX: neg_ #指定负采样前缀
LABEL_FIELD: label #指定标签域
#因为数据集没有标签，所以设置一个阈值，认为rating高于该值的是正例，反之是负例
threshold:
    play_hours: 1
#指定从什么文件里读什么列，这里就是从ml-1m.inter里面读取user_id, item_id, rating, timestamp这四列,剩下的以此类推
load_col:
    inter: [user_id,product_id,play_hours]  #'*' #[user_id,product_id,play_hours,times]
    item: [product_id]
## training settings
epochs: 50 #训练的最大轮数
train_batch_size: 4096 #训练的batch_size
learner: adam #使用的pytorch内置优化器
learning_rate: 0.001 #学习率
training_neg_sample_num: 0 #负采样数目
eval_step: 1 #每次训练后做evalaution的次数
stopping_step: 10 #控制训练收敛的步骤数，在该步骤数内若选取的评测标准没有什么变化，就可以提前停止了
## evalution settings
eval_setting: RO_RS #对数据随机重排，设置按比例划分数据集
group_by_user: True #是否将一个user的记录划到一个组里
split_ratio: [0.8,0.1,0.1] #切分比例
metrics: ['AUC', 'LogLoss'] #评测标准
valid_metric: AUC #选取哪个评测标准作为作为提前停止训练的标准
eval_batch_size: 4096 #评测的batch_size`

I use the DeepFM model, and what the blog says is that there is no full in the context model.
![5](https://user-images.githubusercontent.com/88365677/142849668-2d22647a-a82f-4862-9c86-035646a11a80.png)

Then, I fix it according to the method you just used, and the error is as follows:
![6](https://user-images.githubusercontent.com/88365677/142849913-c5732714-dcf0-4c0b-9ecf-b0256bf7002a.png)

**Comment by chenyuwuxin** [comment] 2021-11-22 12:00
@1xiaohui The problem is that the user you specified has no historical interaction information.In `steam-merged` dataset, the number of users and interactions are very similar.You can make repeatable recommendations by modifying the `full_sort_scores` function like this:
```
@torch.no_grad()
def full_sort_scores(uid_series, model, test_data, device=None):
    """Calculate the scores of all items for each user in uid_series.

    Note:
        The score of [pad] and history items will be set into -inf.

    Args:
        uid_series (numpy.ndarray or list): User id series.
        model (AbstractRecommender): Model to predict.
        test_data (FullSortEvalDataLoader): The test_data of model.
        device (torch.device, optional): The device which model will run on. Defaults to ``None``.
            Note: ``device=None`` is equivalent to ``device=torch.device('cpu')``.

    Returns:
        torch.Tensor: the scores of all items for each user in uid_series.
    """
    device = device or torch.device('cpu')
    uid_series = np.array(uid_series)
    uid_field = test_data.dataset.uid_field
    dataset = test_data.dataset
    model.eval()
    index = np.isin(test_data.user_df[uid_field].numpy(), uid_series)
    input_interaction = test_data.user_df[index]
    # Get scores of all items
    input_interaction = input_interaction.to(device)
    try:
        scores = model.full_sort_predict(input_interaction)
    except NotImplementedError:
        input_interaction = input_interaction.repeat(dataset.item_num)
        input_interaction.update(test_data.dataset.get_item_feature().to(device).repeat(len(uid_series)))
        scores = model.predict(input_interaction)

    scores = scores.view(-1, dataset.item_num)
    scores[:, 0] = -np.inf  # set scores of [pad] to -inf
    return scores
```

**Comment by 1xiaohui** [comment] 2021-11-23 06:04
@chenyuwuxin Thank you for your patience! If i change to the above, there will be new mistakes.
![1](https://user-images.githubusercontent.com/88365677/142977428-5dff11eb-ed9c-4aa0-ba57-69bf9543b214.jpg)
 
I tried to experiment with the not_merged dataset, and the results still showed the previous mistakes. I don't quite understand that there are so many mistakes when using the steam dataset as case_study.
Is there something wrong with my. yaml file?

**Comment by chenyuwuxin** [comment] 2021-11-23 09:39
@1xiaohui Generally speaking, we cannot use `case_study` to predict `context-aware` models.This is because there is an interaction context construction problem of negative examples.We cannot construct the context interaction information of user-item pairs that do not exist in `.inter` file.Therefore,for a user,you can't predict his clicks on all items.For a user, you can only predict the items he has interacted with in the dataset.I provide you with a way(`case_study_for_context`) to predict the interactions that a particular user has had in the dataset.I hope my answer can help you.
```

"""
Case study example
===================
Here is the sample code for the case study in RecBole.
"""


import torch
from recbole.utils.case_study import full_sort_topk, full_sort_scores
from recbole.quick_start import load_data_and_model


if __name__ == '__main__':
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file='saved/DeepFM-Nov-23-2021_16-05-12.pth',
    )  # Here you can replace it by your model path.

    # uid_series = np.array([1, 2])  # internal user id series
    # or you can use dataset.token2id to transfer external user token to internal user id
    uid_series = dataset.token2id(dataset.uid_field, ['196', '186'])

    import numpy as np
    device = config['device']
#    topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=10, device=device)

    uid_series = torch.Tensor(uid_series)
    dataset = test_data.dataset
    model.eval()
    index = []
    for idx , uid in enumerate(dataset.inter_feat[dataset.uid_field]):
        if uid in uid_series:
            index.append(idx)
    index = np.array(index)
    input_interaction = dataset.inter_feat[index]
    user_id = input_interaction[dataset.uid_field]
    item_id = input_interaction[dataset.iid_field]
    input_interaction.update(dataset.user_feat[user_id])
    input_interaction.update(dataset.item_feat[item_id])
    # Get scores of all items
    input_interaction = input_interaction.to(device)

    external_user_list = dataset.id2token(dataset.uid_field, user_id.cpu())
    external_item_list = dataset.id2token(dataset.iid_field, item_id.cpu())
    scores = model.predict(input_interaction)
    print('usr_id: ',external_user_list)
    print('item_id: ',external_item_list)
    print(scores)

```

**Comment by 1xiaohui** [comment] 2021-12-08 11:50
@chenyuwuxin Your answer is very helpful. Now I can get the results. Another question is, what should I modify if I want to get top20 recommendations? At present, I only modify the topk: [20] in the. yaml file, but it will give an error.

**Comment by 1xiaohui** [comment] 2021-12-09 09:49
@chenyuwuxin Why is the AUC value getting smaller and smaller with training? Shouldn't the bigger the better?
![微信截图_20211209174633](https://user-images.githubusercontent.com/88365677/145373254-c9239a0f-c389-4002-bb96-1f7a30907bd7.png)

**Comment by chenyuwuxin** [comment] 2021-12-11 01:16
@1xiaohui Yes, the greater the value of AUC, the better.  However, the value of AUC is calculated from the valid dataset or test dataset in the evaluation stage. Its performance completely depends on the quality of model training. In other words, with the increase of training time, AUC is bound to decline. Btw,for discussion on new topics, it is suggested to open new issue or discussion.

**Closed** 2022-02-21 08:12 UTC
Labels: question

**Comment by afreenneda** [comment] 2025-03-11 15:58
Hello! I was trying to run knowledge based model(CKE) from Recbole. As my data is very sparse(0.0019), I am getting error "ValueError: Some users have interacted with all items, which we can not sample negative items for them. Please set `user_inter_num_interval` to filter those users." How to solve this issue to run knowledge based model on sparse data, kindly help me out.

**Comment by bruno686** [comment] 2025-04-17 08:16
> Hello! I was trying to run knowledge based model(CKE) from Recbole. As my data is very sparse(0.0019), I am getting error "ValueError: Some users have interacted with all items, which we can not sample negative items for them. Please set `user_inter_num_interval` to filter those users." How to solve this issue to run knowledge based model on sparse data, kindly help me out.

I also meet the problem. It's so strange.
